export const constants = {
  ASSET_TAB: "Asset",
  ISSUER_TAB: "Issuer",
  STATIC_TAB: "Static",
  LOAD_ASSET_TAGS: "LOAD_ASSET_TAGS",
  LOAD_ISSUER_TAGS: "LOAD_ISSUER_TAGS",
  LOAD_STATIC_TAGS: "LOAD_STATIC_TAGS",
  ADD_ASSET_TAGS: "ADD_NEW_TAG",
  ADD_ISSUER_TAGS: "ADD_ISSUER_TAGS",
  ADD_STATIC_TAGS: "ADD_STATIC_TAGS",
  DELETE_TAG: "DELETE_TAG",
  LOAD_ALL_TEMPLATES: "LOAD_ALL_TEMPLATES",
  SAVE_TEMPLATE_FIELDS: "SAVE_TEMPLATE_FIELDS",
  STORE_SAVED_TAGS: "STORE_SAVED_TAGS",
  SET_ACTIVE_PAGE_NOTE_ID: "SET_ACTIVE_PAGE_NOTE_ID",
  SET_PUSH_NOTES_BUTTON_STATE: "SET_PUSH_NOTES_BUTTON_STATE",
  SET_SELECTED_TEMPLATE: "SET_SELECTED_TEMPLATE"
};
